use crate::source::Span;

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Keyword(Keyword),
    Identifier(String),
    Number(NumberLiteral),
    String(String),
    Symbol(String),
    Newline,
    Eof,
}

#[derive(Clone, Debug, PartialEq)]
pub enum NumberLiteral {
    Int(i64),
    Float(f64),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Keyword {
    Marmot,
    Insane,
    Dig,
    Let,
    Stash,
    Return,
    If,
    Else,
    For,
    In,
    While,
    Break,
    Continue,
    True,
    False,
    Null,
    Matrix,
    Burrow,
    Use,
    Squeak,
    Sniff,
    Panic,
    Try,
    Catch,
    Tunnel,
    Choose,
    Den,
    Hatch,
    SelfValue,
    Init,
    Fur,
    Fang,
    Mask,
    Wear,
    Under,
    Web,
    Fetch,
    Grab,
    Howl,
    Wait,
    Scatter,
    Nest,
    Nap,
    Tick,
    Pack,
    Crate,
    Pelt,
    Probe,
    Law,
    Expect,
    Trace,
}

impl Keyword {
    pub fn parse(text: &str) -> Option<Self> {
        Some(match text {
            "marmot" => Self::Marmot,
            "insane" => Self::Insane,
            "dig" => Self::Dig,
            "let" => Self::Let,
            "stash" => Self::Stash,
            "return" => Self::Return,
            "if" => Self::If,
            "else" => Self::Else,
            "for" => Self::For,
            "in" => Self::In,
            "while" => Self::While,
            "break" => Self::Break,
            "continue" => Self::Continue,
            "true" => Self::True,
            "false" => Self::False,
            "null" => Self::Null,
            "matrix" => Self::Matrix,
            "burrow" => Self::Burrow,
            "use" => Self::Use,
            "squeak" => Self::Squeak,
            "sniff" => Self::Sniff,
            "panic" => Self::Panic,
            "try" => Self::Try,
            "catch" => Self::Catch,
            "tunnel" => Self::Tunnel,
            "choose" => Self::Choose,
            "den" => Self::Den,
            "hatch" => Self::Hatch,
            "self" => Self::SelfValue,
            "init" => Self::Init,
            "fur" => Self::Fur,
            "fang" => Self::Fang,
            "mask" => Self::Mask,
            "wear" => Self::Wear,
            "under" => Self::Under,
            "web" => Self::Web,
            "fetch" => Self::Fetch,
            "grab" => Self::Grab,
            "howl" => Self::Howl,
            "wait" => Self::Wait,
            "scatter" => Self::Scatter,
            "nest" => Self::Nest,
            "nap" => Self::Nap,
            "tick" => Self::Tick,
            "pack" => Self::Pack,
            "crate" => Self::Crate,
            "pelt" => Self::Pelt,
            "probe" => Self::Probe,
            "law" => Self::Law,
            "expect" => Self::Expect,
            "trace" => Self::Trace,
            _ => return None,
        })
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Marmot => "marmot",
            Self::Insane => "insane",
            Self::Dig => "dig",
            Self::Let => "let",
            Self::Stash => "stash",
            Self::Return => "return",
            Self::If => "if",
            Self::Else => "else",
            Self::For => "for",
            Self::In => "in",
            Self::While => "while",
            Self::Break => "break",
            Self::Continue => "continue",
            Self::True => "true",
            Self::False => "false",
            Self::Null => "null",
            Self::Matrix => "matrix",
            Self::Burrow => "burrow",
            Self::Use => "use",
            Self::Squeak => "squeak",
            Self::Sniff => "sniff",
            Self::Panic => "panic",
            Self::Try => "try",
            Self::Catch => "catch",
            Self::Tunnel => "tunnel",
            Self::Choose => "choose",
            Self::Den => "den",
            Self::Hatch => "hatch",
            Self::SelfValue => "self",
            Self::Init => "init",
            Self::Fur => "fur",
            Self::Fang => "fang",
            Self::Mask => "mask",
            Self::Wear => "wear",
            Self::Under => "under",
            Self::Web => "web",
            Self::Fetch => "fetch",
            Self::Grab => "grab",
            Self::Howl => "howl",
            Self::Wait => "wait",
            Self::Scatter => "scatter",
            Self::Nest => "nest",
            Self::Nap => "nap",
            Self::Tick => "tick",
            Self::Pack => "pack",
            Self::Crate => "crate",
            Self::Pelt => "pelt",
            Self::Probe => "probe",
            Self::Law => "law",
            Self::Expect => "expect",
            Self::Trace => "trace",
        }
    }
}
